---
- name: Activate grafana for hosts
  replace:
    path: '/opt/omd/sites/{{omd_site}}/etc/nagios/conf.d/check_mk_templates.cfg'
    regexp: 'pnp4nagios/index.php/graph\?host=\$HOSTNAME\$&srv=_HOST_.*$'
    replace: 'grafana/dashboard/script/histou.js?host=$HOSTNAME$&theme=light&annotations=true'
  notify: Reload omd

- name: Activate grafana for services
  replace:
    path: '/opt/omd/sites/{{omd_site}}/etc/nagios/conf.d/check_mk_templates.cfg'
    regexp: 'pnp4nagios/index.php/graph\?host=\$HOSTNAME\$&srv=\$SERVICEDESC\$.*$'
    replace: 'grafana/dashboard/script/histou.js?host=$HOSTNAME$&service=$SERVICEDESC$&theme=light&annotations=true'
  notify: Reload omd

- name: Install mod_ldap if LDAP
  yum: name=mod_ldap state=present
  when: omd_ldap_enabled

- name: Configure LDAP authentication in apache
  template: dest='/opt/omd/sites/{{omd_site}}/etc/apache/conf.d/auth.conf' src=auth.conf.j2 owner={{omd_site}} group={{omd_site}} mode=0644
  notify: Reload omd

- name: Activate LDAP in grafana
  ini_file: path='/opt/omd/sites/{{omd_site}}/etc/grafana/grafana.ini' section='{{item.section}}' option='{{item.option}}' value='{{item.value}}' owner={{omd_site}} group={{omd_site}} mode=0644
  with_items:
    - {section: 'auth.ldap', option: 'enabled', value: 'false'}
    - {section: 'auth.ldap', option: 'config_file', value: '/omd/sites/{{omd_site}}/etc/grafana/ldap.toml'}
  notify: Reload omd

- name: Configure user creation and login in grafana
  ini_file: path='/opt/omd/sites/{{omd_site}}/etc/grafana/grafana.ini' section='{{item.section}}' option='{{item.option}}' value='{{item.value}}' owner={{omd_site}} group={{omd_site}} mode=0644
  with_items:
    - {section: 'auth', option: 'disable_login_form', value: 'true'}
    - {section: 'users', option: 'allow_org_create', value: 'false'}
    - {section: 'users', option: 'auto_assign_org', value: 'true'}
    - {section: 'users', option: 'allow_sign_up', value: 'false'}
  notify: Reload omd

- name: Configure dashboards
  ini_file: path='/opt/omd/sites/{{omd_site}}/etc/grafana/grafana.ini' section='{{item.section}}' option='{{item.option}}' value='{{item.value}}' owner={{omd_site}} group={{omd_site}} mode=0644
  with_items:
    - {section: 'dashboard.json', option: 'path', value: '/omd/sites/monit1/var/grafana/dashboards'}
  notify: Reload omd

- name: Configure LDAP connection in grafana
  template: dest='/opt/omd/sites/{{omd_site}}/etc/grafana/ldap.toml' src=ldap.toml.j2 owner={{omd_site}} group={{omd_site}} mode=0644
  when: omd_ldap_enabled
  notify: Reload omd
